### ISSUE TITLE
Using sanic_transmute

### ISSUE THREAD

**Issue by guipat** [lordent/sanic-boilerplate#1]
Hello ! 
I find your boilerplate interesting, what about using sanic_transmute in your boilerplate ?
see here : http://sanic-transmute.readthedocs.io/en/latest/

Kind regards

**Comment by lordent** [comment]
Hi, @guipat 
My boilerplate in draft. I dont like transmute module. For me, using the marshmallow module is much more convenient.
And I need a tool for create a complete description of openapi documentation
for example: https://github.com/lordent/sanic-boilerplate/blob/master/api/content/welcome.py

Thanks for question

**Comment by guipat** [comment]
alright ! I'll dig into your boilerplate to get used to it, thanks for answering so quickly 👍
