### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by gustelle** [lordent/sanic-boilerplate#2]
Hello !

I find your boilerplate nice, I propose to contribute with a README, are you interested ?

**Comment by lordent** [comment]
@gustelle hi

Of Course u can

**Comment by gustelle** [comment]
great, I tried to push a readme but when typing` git push origin my-branch-name` I get an error 
`remote: Permission to lordent/sanic-boilerplate.git denied to gustelle`

Is there any restriction on the project ?

**Comment by lordent** [comment]
@gustelle yes, u can make pull requests
